project:
  type: website
  output-dir: docs

website:
  title: "Learn WGPU-rs"
  site-url: https://github.com/inkfin/LearnWGPU-rs
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        url: https://github.com/inkfin/LearnWGPU-rs
    contents:
      - href: index.qmd
        text: Home
      - section: "Slides"
        contents: slides/*
      - section: "Demos"
        contents:
          - demos/example_cube/index.qmd
          - demos/example_fish/index.qmd
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



